// styles/themes.js

const themes = {
  light: {
    background: "#f0f0f0",
    text: "#000",
    buttonBackground: "#e0e0e0",
    buttonText: "#000",
    buttonEdit: "#4caf50",
    buttonDelete: "#f44336",
    border: "#ddd",
    contactBackground: "#fff",
  },
  dark: {
    background: "#333",
    text: "#fff",
    buttonBackground: "#555",
    buttonText: "#fff",
    buttonEdit: "#4caf50",
    buttonDelete: "#f44336",
    border: "#444",
    contactBackground: "#222",
  },
  lightBlue: {
    background: "#e3f2fd",
    text: "#0277bd",
    buttonBackground: "#b3e5fc",
    buttonText: "#0277bd",
    buttonEdit: "#039be5",
    buttonDelete: "#d32f2f",
    border: "#81d4fa",
    contactBackground: "#ffffff",
  },
  pink: {
    background: "#fce4ec",
    text: "#880e4f",
    buttonBackground: "#f8bbd0",
    buttonText: "#880e4f",
    buttonEdit: "#d81b60",
    buttonDelete: "#c2185b",
    border: "#f48fb1",
    contactBackground: "#ffffff",
  },
  darkOrange: {
    background: "#212121",
    text: "#ffab00",
    buttonBackground: "#424242",
    buttonText: "#ffab00",
    buttonEdit: "#ff5722",
    buttonDelete: "#ff7043",
    border: "#616161",
    contactBackground: "#303030",
  },
  green: {
    background: "#e8f5e9",
    text: "#388e3c",
    buttonBackground: "#c8e6c9",
    buttonText: "#388e3c",
    buttonEdit: "#2e7d32",
    buttonDelete: "#c62828",
    border: "#a5d6a7",
    contactBackground: "#ffffff",
  },
  purple: {
    background: "#f3e5f5",
    text: "#6a1b9a",
    buttonBackground: "#e1bee7",
    buttonText: "#6a1b9a",
    buttonEdit: "#8e24aa",
    buttonDelete: "#d81b60",
    border: "#ce93d8",
    contactBackground: "#ffffff",
  },
  teal: {
    background: "#e0f2f1",
    text: "#004d40",
    buttonBackground: "#b2dfdb",
    buttonText: "#004d40",
    buttonEdit: "#00796b",
    buttonDelete: "#004d40",
    border: "#80cbc4",
    contactBackground: "#ffffff",
  },
  amber: {
    background: "#fff8e1",
    text: "#ff6f00",
    buttonBackground: "#ffe082",
    buttonText: "#ff6f00",
    buttonEdit: "#ffb300",
    buttonDelete: "#f57f17",
    border: "#ffecb3",
    contactBackground: "#ffffff",
  },
};

export default themes;
